variable "vpc_cidr_block" {}
variable "environment_name" {}
variable "region" {}
variable "image_id" {}
variable "instance_type" {}
variable "min_size" {}
variable "max_size" {}
variable "desired_capacity" {}
variable "Instance_profile_name" {}
variable "role_name" {}
variable "custom_policy_name" {}
variable "bucket_prefix" {}
variable "db_username" {}
variable "project_name" {}
variable "cpu_high_threshold" {}
variable "cpu_low_threshold" {}